### ISSUE TITLE
Add sorting algorithms, any language !

### ISSUE THREAD

**Issue by Nikzy7** [Nikzy7/Algorithm-Snippets#1]
Please mention the sorting algorithm and the language you'll be working upon. Do not forget to go through README.md. Please mention issue number in the PR. Help the people who are new to Open-Source !

**Comment by TanayKulkarni** [comment]
Shall I work on this?

**Comment by Nikzy7** [comment]
@TanayKulkarni sure !! Just mention the algorithms and language. Also, please go through the README too !! Happy hacktoberfest!

**Comment by TanayKulkarni** [comment]
I'll be sharing merge, quick, selection, and insertion sort algorithms in Python

**Comment by TanayKulkarni** [comment]
Can this be assigned to me please! Also, do you want me to create a folder just for python solutions?

**Comment by Nikzy7** [comment]
@TanayKulkarni yes please 😄

**Comment by NEENA-XAVIER** [comment]
I like to heap sort in Python!

**Comment by adi0311** [comment]
I can add Counting Sort, Radix Sort and Bucket Sort in Python. Can you please assign this to me?

**Comment by adi0311** [comment]
Added Counting Sort, Radix Sort and Bucket Sort in Python :-)

**Comment by rykulkarni** [comment]
Added bubble sort in python #29

**Comment by Cirediallo** [comment]
I'll share InsertSort in Java

**Comment by Nikzy7** [comment]
@Cirediallo go ahead !

**Comment by praneethacl** [comment]
Can I add Shell Sort program in python?

**Comment by Nikzy7** [comment]
@praneethacl assigning you shell sort !

**Comment by tusharrao198** [comment]
Can I work on this?  I will be writing these codes in cpp.  
heap sort , merge sort, insertion sort , quick sort.

**Comment by AlessandroArosio** [comment]
Can I contribute with quick sort in Java?
On a separate PR, I'd like to write some sorting techniques in GoLang

**Comment by Nikzy7** [comment]
@tusharrao198 we already have PR for insertion and merge. Assigning you for heap and quick !

**Comment by Nikzy7** [comment]
@AlessandroArosio sorry we have already have quicksort for java. Although you can make a PR for that, i'll mark it hacktoberfest-accepted. For GoLang, i'll be really grateful if you could do that. Please follow the directory structure mentioned in the README 😄

**Comment by kylejosterman** [comment]
Can I add merge sort in Java?

**Comment by Nikzy7** [comment]
@kylejosterman sorry we already have that ! you can create a PR though, I'll mark it hacktoberfest-accepted

**Comment by kylejosterman** [comment]
@Nikzy7 Ahh my bad, I can work on selection sort in Java

**Comment by Nikzy7** [comment]
Well, we have that too. Really sorry for that ! we don't have Radix or shell sort though ! And yeah don't worry, you can still create a PR.

**Comment by kylejosterman** [comment]
@Nikzy7 Hahaha I see, I can do radix sort

**Comment by Nikzy7** [comment]
@kylejosterman assigning you now ! Happy hacktoberfest !

**Comment by AlistairMcKellar** [comment]
I'll have a go at C# merge sort

**Comment by RahulRS246** [comment]
i will do counting sort in java

**Comment by Cirediallo** [comment]
I've add bubble sort algorithm in Java. will you check it

**Comment by Alisha-Ahmed** [comment]
Hey,can you assign it to me

**Comment by Nikzy7** [comment]
@Alisha-Ahmed what algo would you like to work on?

**Comment by Alisha-Ahmed** [comment]
Bubble sort,linear and binary search in C

**Comment by Nikzy7** [comment]
Sure, go ahead ! Please take a look at the README and follow the directory structure !

**Comment by Alisha-Ahmed** [comment]
Okay...Thank you

**Comment by praneethacl** [comment]
Can I add Heap_Sort in c++?

**Comment by Nikzy7** [comment]
@praneethacl go ahead!

**Comment by praneethacl** [comment]
Can I add Counting Sort in Cpp?

**Comment by Nikzy7** [comment]
@praneethacl sure !

**Comment by Alisha-Ahmed** [comment]
@Nikzy7 I have added the 3 algorithms.Please Check.

**Comment by kartikeyaGUPTA45** [comment]
@Nikzy7,  Can I add Radix Sort in C++ language
Please assign to me

**Comment by kartikeyaGUPTA45** [comment]
@Nikzy7, Can I Bubble sort in c++ language

**Comment by kartikeyaGUPTA45** [comment]
@Nikzy7, Can I add Bucket sort in c++ language. Please assign to me
