### ISSUE TITLE
Add popular/interview_specific algorithms, any language !

### ISSUE THREAD

**Issue by Nikzy7** [Nikzy7/Algorithm-Snippets#2]
Please go through the README.md first. Maintain the spirit of Open-Source. Mention the algorithm and language you'll be working upon in the comments. Happy hacktoberfest !

**Comment by Mownika25** [comment]
Can I add some coding question answers asked in my interview in java?

**Comment by Nikzy7** [comment]
@Mownika25 Sure go ahead ! Just create a new folder named "Interview Questions" and in comments add some description please. It'll be really helpful.

**Comment by NirmalSilwal** [comment]
Hi @Nikzy7, I would like to add few important coding interview questions. I will add the implementation in Java. Shall I proceed?

**Comment by Nikzy7** [comment]
@NirmalSilwal sure ! Sorry for the late response !

**Comment by NirmalSilwal** [comment]
Hi @Nikzy7, please review my PR #36 and do let me know.

**Comment by anmol193** [comment]
can i solve this issue?

**Comment by Nikzy7** [comment]
@anmol193 Sure !

**Comment by kkkkkabir** [comment]
Hey! Can I work on this issue?

**Comment by Nikzy7** [comment]
@kkkkkabir sure!

**Comment by kkkkkabir** [comment]
Hi @Nikzy7 , please review my PR #76

**Comment by susmita2000** [comment]
Hi !could you please review my PR. I have added insertion and selection sorts in c++

**Comment by susmita2000** [comment]
Can I add some interview questions in C++?

**Comment by Nikzy7** [comment]
@susmita2000 sure !

**Comment by Riddhima23** [comment]
hey!I am new and wanna add something

**Comment by Nikzy7** [comment]
@Riddhima23 sure go ahead !

**Comment by AkashDeep2924** [comment]
Can I add some problems related to DSA ?

**Comment by Nikzy7** [comment]
@AkashDeep2924 can you do that in my other repo https://github.com/Nikzy7/Data-Structures-Snippets.git
i haven't put it up for hacktoberfest RN, but i'll put hactoberfest-accepted label for your PR

**Comment by AkashDeep2924** [comment]
Okay Thank You

**Comment by Alisha-Ahmed** [comment]
Hey could you please assign this to me ?

**Comment by ShantiMow** [comment]
Can I do this?

**Comment by spartaabhishek** [comment]
i would like to add heap sort using python @Nikzy7
