### ISSUE TITLE
Add A* Search Algorithm in python, java and C++

### ISSUE THREAD

**Issue by redet-G** [Nikzy7/Algorithm-Snippets#28]
Implement A* search algorithm

**Comment by ebeohp** [comment]
I'm interested in contributing a java file for this :)

**Comment by RadientBrain** [comment]
Hi, I want to contribute to your repo using python. please assign this to me!

**Comment by RadientBrain** [comment]
I have made a **PR** ( PR no. #38 ) which resolves this issue for the python language.
Please consider it for merging!

**Comment by Nikzy7** [comment]
@ebeohp go ahead ! assigning you for java

**Comment by ebeohp** [comment]
I made a PR #45 :)

**Comment by anmol193** [comment]
can i do it in C++ ?

**Comment by Nikzy7** [comment]
@anmol193 addigning you for C++ and closing this issue ! Happy Hacktoberfest !
