### ISSUE TITLE
Kadane's Algorithm any language !

### ISSUE THREAD

**Issue by Nikzy7** [Nikzy7/Algorithm-Snippets#56]
Please add a good explanation as comment. Ask for assign with one language per PR only ! Help the new-comers! Happy hacktoberfest.

**Comment by kartikeyaGUPTA45** [comment]
@Nikzy7, Assign Kadane's Algorithm to me in C++

**Comment by Ruchika8** [comment]
Assign it to me for java!

**Comment by praneethacl** [comment]
I can do this in python.

**Comment by Nikzy7** [comment]
if anybody is up for any other language please drop a comment. Else closing this issue by 3.30 p.m. IST.
