### ISSUE TITLE
Please add quicksort in java and cpp !

### ISSUE THREAD

**Issue by Nikzy7** [Nikzy7/Algorithm-Snippets#6]
please take a look at README.md ! Good for newcomers

**Comment by Harsh-Udai** [comment]
hey @Nikzy7  can you assign this to me , i like on work on this

**Comment by Nikzy7** [comment]
Sure ! Go ahead @HarshUdai ! Just take a look at readme first regarding the file structure

**Comment by Harsh-Udai** [comment]
Hey @Nikzy7 , i have made a pr please check.
