### ISSUE TITLE
Add Rust programs !

### ISSUE THREAD

**Issue by Nikzy7** [Nikzy7/Algorithm-Snippets#64]
Help the people who have just begun diving into the world of rust ! Add any rust program. Just mention in the code (as a comment) the level of the program (beginner/intermediate/advanced). Please follow the directory structure explained in README. Happy hacktoberfest !

**Comment by Nikzy7** [comment]
@Dr-Badass would you like to work on this ?

**Comment by Dr-Badass** [comment]
Why not :)

**Comment by kartikeyaGUPTA45** [comment]
@Nikzy7  assign Addition Program to me (Beginner)

**Comment by Nikzy7** [comment]
@kartikeyaGUPTA45 Sure go ahead !

**Comment by Satya388** [comment]
@Nikzy7  assign me some rust programs
