### ISSUE TITLE
Add binary search in Java, Python, C++ !

### ISSUE THREAD

**Issue by Nikzy7** [Nikzy7/Algorithm-Snippets#7]
Good for newcomers. Creating an Algo snippet repo. All PRs are welcome. Take a look at README and mention your language of choice !

**Comment by sonuishaq67** [comment]
I can do java and c++
assign me for this

**Comment by Nikzy7** [comment]
@sonuishaq67 go ahead !!!! 👍

**Comment by Mathur777** [comment]
I can do it in java 
please assign me

**Comment by Nikzy7** [comment]
@Mathur777 I'll have to compare your PR with @sonuishaq67 but I'll definitely mark your PRs with hacktoberfest-accepted label !

**Comment by suprimnakarmi** [comment]
I can do it in python.
please assign!!

**Comment by Nikzy7** [comment]
@suprimnakarmi assigning you python ! closing this issue after your PR ! thank you all for your contributions. Happy Hacktoberfest !

**Comment by suprimnakarmi** [comment]
#25

**Comment by suprimnakarmi** [comment]
#25 PR created!!. Thank you @Nikzy7

**Comment by Nikzy7** [comment]
Thank you all for your contribution !
