### ISSUE TITLE
Add Linear Search in python, java C++

### ISSUE THREAD

**Issue by Nikzy7** [Nikzy7/Algorithm-Snippets#8]
Good for newcomers ! Take a look at README. All PRs are welcome. Mention the language of your choice in the comments. Any other language? Just follow the directory structure explained in README. Happy Hactoberfest !

**Comment by sonuishaq67** [comment]
I can do the java and c++ part for this !
assign me for this !

**Comment by Alisha-Ahmed** [comment]
Hey,I can do it in Python,C,C++ and Java.Could you assign it to me.

**Comment by Nikzy7** [comment]
@Alisha-Ahmed Go ahead !

**Comment by Alisha-Ahmed** [comment]
😀Thank You

**Comment by SarthakM7** [comment]
Added linear search in python and quick sort in cpp (both were missing). Thanks.

**Comment by avk29** [comment]
Hi!, i've added linear search in python #30 . let me know if any changes are required
