### ISSUE TITLE
Add Merge Sort in java,c++, python !

### ISSUE THREAD

**Issue by Nikzy7** [Nikzy7/Algorithm-Snippets#9]
Good for newcomers ! Take a look at README. All PRs are welcome. Mention the language of your choice in the comments. Any other language? Just follow the directory structure explained in README. Happy Hactoberfest !

**Comment by PratikshaGoyal** [comment]
I would like to work on this issue. Please assign it to me !

**Comment by Nikzy7** [comment]
@PratikshaGoyal Go ahead 👍

**Comment by SarthakM7** [comment]
Hey ! I'd like to work on it. Please assign it to me if possible.

**Comment by Nikzy7** [comment]
@SarthakM7 I am sorry but it has already been assigned to @PratikshaGoyal ... You can create a PR if you want, I'll compare and merge accordingly. I'll definitely add the label hacktoberfest-accepted so your entry will be counted.

**Comment by Mownika25** [comment]
Can I write the program for java? Can you assign this to me?

**Comment by Nikzy7** [comment]
@Mownika25  go ahead... i have PRs from @SarthakM7 in cpp, and @PratikshaGoyal in python .... I'll be closing this issue ! Happy hacktoberfest everyone !

**Comment by Nikzy7** [comment]
Thank you everyone for their contributions 👍 you all are awesome ! closing this issue now
